version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: donation_platform
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
